spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/dev_db
          username: postgres
          password: 123456
  jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true

---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_db
    username: postgres
    password: 123456
